-LC:\BCC55\lib\obj;C:\BCC55\lib;\xHWGUI\xharbour\lib -Gn -M -m -s -Tpe -x -aa +
c0w32.obj obj\RHESOCIAL.obj, +
esocial.exe,, +
lang.lib vm.lib rtl.lib rdd.lib macro.lib pp.lib dbfntx.lib dbfcdx.lib dbffpt.lib common.lib gtwvw.lib  codepage.lib ct.lib tip.lib pcrepos.lib hsx.lib hbsix.lib  hwgui.lib import32.lib cw32.lib, +
, +

